services:
    postgres:
        image: postgres
        container_name: "project-gallery-db"

        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

        healthcheck:
            test: pg_isready -U postgres -d postgres
            interval: 10s
            timeout: 3s
            retries: 3

        ports:
            - 5432:5432

        networks:
            - project-gallery

        volumes:
            - db-data:/var/lib/postgresql/data

        command: postgres -c listen_addresses='*'

    runner:
        build:
            context: .
            dockerfile: Dockerfile.runner
        container_name: "project-gallery-runner"

        networks:
            - project-gallery

        depends_on:
            - postgres

        environment:
            DATABASE_URL: "postgresql://postgres:postgres@project-gallery-db:5432/postgres?schema=public"

        ports:
            - 4000:4000

    app:
        build: .
        container_name: "project-gallery"

        networks:
            - project-gallery

        depends_on:
            - postgres

        environment:
            DATABASE_URL: "postgresql://postgres:postgres@project-gallery-db:5432/postgres?schema=public"

        ports:
            - 3000:3000

networks:
    project-gallery:

volumes:
    db-data:
